__title__ = 'utils'
__version__ = '0.0.1'
__author__ = 'JuanFe98'
__email__ = 'jmartinezbernal02@gmail.com'
__description__ = 'Modulo de utilidades de Python'
__url__ = 'https://github.com/JuanFeA98/Utils_py'